[package]
name = "reflux"
version = "1.0.2"
edition = "2021"
license = "GPL-3.0"
homepage = "https://github.com/kyleb000/reflux/wiki"
repositiory = "https://github.com/kyleb000/reflux"
description = "A mechanism for writing rigorous code based on a distributed computing concept."
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam-channel = "0.5.4"
anyhow = "1.0.82"