[package]
name = "reflux"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0"
homepage = "https://github.com/kyleb000/reflux/wiki"
repositiory = "https://github.com/kyleb000/reflux"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
